-- =============================================================================
-- AgAI_22 PM Automation Agent — Supabase Schema
-- Run once in the Supabase SQL editor.
-- All tables use the pm_ prefix. Safe to re-run (idempotent).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- pm_items
-- Persists every captured item after Triage and Prioritizer agents run.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pm_items (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source              TEXT NOT NULL,
    item_type           TEXT NOT NULL,
    title               TEXT NOT NULL,
    summary             TEXT,
    priority_level      TEXT NOT NULL,
    priority_score      INTEGER,
    project_hint        TEXT,
    assignee_hint       TEXT,
    due_date_hint       DATE,
    tags                TEXT[],
    notion_page_id      TEXT,
    raw_content         TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pm_items_source         ON pm_items (source);
CREATE INDEX IF NOT EXISTS idx_pm_items_priority_level ON pm_items (priority_level);
CREATE INDEX IF NOT EXISTS idx_pm_items_item_type      ON pm_items (item_type);
CREATE INDEX IF NOT EXISTS idx_pm_items_created_at     ON pm_items (created_at DESC);

COMMENT ON TABLE pm_items IS
    'All captured action items after triage and prioritization.';


-- -----------------------------------------------------------------------------
-- pm_agent_results
-- Persists the raw output of every agent run for tracing and debugging.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pm_agent_results (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_name      TEXT NOT NULL,
    input_ref       TEXT,
    output          JSONB,
    status          TEXT NOT NULL DEFAULT 'success',
    error_message   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pm_agent_results_agent_name  ON pm_agent_results (agent_name);
CREATE INDEX IF NOT EXISTS idx_pm_agent_results_created_at  ON pm_agent_results (created_at DESC);

COMMENT ON TABLE pm_agent_results IS
    'Raw output of every Claude agent run. Used for debugging and tracing.';


-- -----------------------------------------------------------------------------
-- pm_digests
-- Stores every generated daily and weekly digest.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pm_digests (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    digest_type     TEXT NOT NULL CHECK (digest_type IN ('daily', 'weekly')),
    subject         TEXT NOT NULL,
    body            TEXT NOT NULL,
    item_count      INTEGER,
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pm_digests_digest_type  ON pm_digests (digest_type);
CREATE INDEX IF NOT EXISTS idx_pm_digests_created_at   ON pm_digests (created_at DESC);

COMMENT ON TABLE pm_digests IS
    'Daily and weekly digests generated by the reviewer and pruner agents.';


-- -----------------------------------------------------------------------------
-- pm_audit_log
-- Append-only event log for every significant system action.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pm_audit_log (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type      TEXT NOT NULL,
    source          TEXT NOT NULL,
    status          TEXT NOT NULL,
    item_id         TEXT,
    payload         JSONB,
    error_message   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pm_audit_log_event_type  ON pm_audit_log (event_type);
CREATE INDEX IF NOT EXISTS idx_pm_audit_log_source       ON pm_audit_log (source);
CREATE INDEX IF NOT EXISTS idx_pm_audit_log_created_at   ON pm_audit_log (created_at DESC);

COMMENT ON TABLE pm_audit_log IS
    'Append-only audit log for all system events, captures, and agent runs.';


-- -----------------------------------------------------------------------------
-- updated_at trigger for pm_items
-- Automatically updates updated_at on every row change.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_pm_items_updated_at ON pm_items;
CREATE TRIGGER trg_pm_items_updated_at
    BEFORE UPDATE ON pm_items
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
